config/routes.rb
Crmapp::Application.routes.draw do
  resources :pessoas

  resources :empresas

  get "principal/index"

  root :to => 'principal#index'

end

app/models/act_as_selectable.rb
module ActAsSelectable
  def options_for_select(name="nome",id="id",*options)
    options=options[0]
    filter=nil
    order=nil
    
    if options !=nil && options.class==Hash
      if options.include?(:filter) && options[:filter].class==Hash
        filter=options[:filter] # :filter=>{:nome=>'lol'} || :filter=>{:ativo=>true}
      end
      if options.include?(:order) && options[:order].class==Hash
        order=options[:order] # :filter=>{:nome=>'lol'} || :filter=>{:ativo=>true}
      end
    end
    
    if filter!=nil
      if order!=nil
        x = self.where(filter.to_a[0][0]=>filter.to_a[0][1]).order(order.to_a[0][0])
      else
        x = self.where(filter.to_a[0][0]=>filter.to_a[0][1]).order(name)
      end
    else
      if order!=nil
        x = self.find(:all,:order=>order.to_a[0][0])
      else
        x = self.find(:all,:order=>name)
      end
    end
    
    select_option_array = []
    x.each do |x|
      select_option_array.push(SelectOption.new(x.send(id),"#{x.send(name)}"))  
    end
    select_option_array
  end
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  
  has_many :pessoas
  
  validates :razao_social, :presence => true, :length => { :maximum => 100 }
  validates :cnpj, :presence => true
  validates :telefone, :presence => true
  validates :website, :presence => true
  
end

app/models/pessoa.rb
#encoding: utf-8
class Pessoa < ActiveRecord::Base
  belongs_to :empresa
  
  def canonical_sexo
    if self.sexo==1
      "♂"
    else
      "♀"
    end
  end
  
end

app/models/select_option.rb
class SelectOption
	attr_accessor :id,:name

	def initialize(id,name)
		@id=id
		@name=name
	end	

  def to_html_option
    "<option value=\"#{self.id}\">#{self.name}</option>"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @empresas }
    end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @empresa }
    end
  end

  # GET /empresas/new
  # GET /empresas/new.json
  def new
    @empresa = Empresa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @empresa }
    end
  end

  # GET /empresas/1/edit
  def edit
    @empresa = Empresa.find(params[:id])
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(params[:empresa])

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render json: @empresa, status: :created, location: @empresa }
      else
        format.html { render action: "new" }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /empresas/1
  # PUT /empresas/1.json
  def update
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      if @empresa.update_attributes(params[:empresa])
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa = Empresa.find(params[:id])
    @empresa.destroy

    respond_to do |format|
      format.html { redirect_to empresas_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pessoas }
    end
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/new
  # GET /pessoas/new.json
  def new
    @pessoa = Pessoa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pessoa }
    end
  end

  # GET /pessoas/1/edit
  def edit
    @pessoa = Pessoa.find(params[:id])
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(params[:pessoa])

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render json: @pessoa, status: :created, location: @pessoa }
      else
        format.html { render action: "new" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pessoas/1
  # PUT /pessoas/1.json
  def update
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      if @pessoa.update_attributes(params[:pessoa])
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa = Pessoa.find(params[:id])
    @pessoa.destroy

    respond_to do |format|
      format.html { redirect_to pessoas_url }
      format.json { head :ok }
    end
  end
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def index
    @manutencao = false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :razao_social %><br />
    <%= f.text_field :razao_social %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1><%= @empresa.razao_social%></h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<h1>Empresas</h1>

<table>
  <tr>
    <th>Razao social</th>
    <th>Telefone</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @empresas.each do |empresa| %>
  <tr>
    <td><%= empresa.razao_social %></td>
    <td><%= empresa.telefone %></td>
    <td><a href="<%= empresa.website %>"><%= empresa.website %></a></td>
    <td><%= link_to 'Mostrar', empresa %></td>
    <td><%= link_to 'Alterar', edit_empresa_path(empresa) %></td>
    <td><%= link_to 'Remover', empresa, confirm: 'Tem certeza?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<h1>Nova empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Razao social:</b>
  <%= @empresa.razao_social %>
</p>

<p>
  <b>Cnpj:</b>
  <%= @empresa.cnpj %>
</p>

<p>
  <b>Telefone:</b>
  <%= @empresa.telefone %>
</p>

<p>
  <b>Website:</b>
  <%= @empresa.website %>
</p>

<p>
  <b>Descricao:</b>
  <%= @empresa.descricao %>
</p>


<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crmapp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<a href="<%= pessoas_path %>">Pessoas</a> | <a href="<%= empresas_path %>">Empresas</a> 
</br>
<%= yield %>

</body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br />
    <%= select(:pessoa, :sexo, [['Masculino', 1], ['Feminino', 2]]) %>
  </div>
  <div class="field">
    <%= f.label :empresa %><br />
    <%= collection_select(:pessoa, :empresa_id, Empresa.all, :id, :razao_social) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<h1>Listing pessoas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Sexo</th>
    <th>Empresa</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pessoas.each do |pessoa| %>
  <tr>
    <td><%= pessoa.nome %></td>
    <td><%= pessoa.canonical_sexo %></td>
    <td><%= pessoa.empresa.razao_social %></td>
    <td><%= link_to 'Show', pessoa %></td>
    <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
    <td><%= link_to 'Destroy', pessoa, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @pessoa.nome %>
</p>

<p>
  <b>Sexo:</b>
  <%= @pessoa.canonical_sexo %>
</p>

<p>
  <b>Empresa:</b>
  <%= @pessoa.empresa.razao_social %>
</p>


<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>

app/views/principal/index.html.erb
<h1>Bem-vindo ao CRM App</h1>
<p>Este software está sendo processado com Ruby versão <%= RUBY_VERSION %></p>

<% if @manutencao == true %>
<p style="color:red;">Este software está em modo de manutenção</p>
<% end %>